#ifndef _MAPS_H_
#define _MAPS_H_

enum MapField {
  EMPTY = 0,
  WALL = 1,
  DEST = 2,
  BOX = 3,
  DEST_BOX = 4,
  PLAYER = 5,
};

const int STAGE1_WIDTH = 10;
const int STAGE1_HEIGHT = 10;
const int STAGE1_MOVES = 20;
const MapField STAGE1[] = {
    WALL, WALL,  WALL,  WALL,   WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  //
    WALL, EMPTY, EMPTY, EMPTY,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  //
    WALL, EMPTY, EMPTY, EMPTY,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  //
    WALL, EMPTY, EMPTY, EMPTY,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  //
    WALL, EMPTY, EMPTY, PLAYER, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  //
    WALL, EMPTY, EMPTY, EMPTY,  EMPTY, EMPTY, EMPTY, BOX,   DEST,  WALL,  //
    WALL, EMPTY, EMPTY, EMPTY,  EMPTY, EMPTY, EMPTY, BOX,   DEST,  WALL,  //
    WALL, EMPTY, EMPTY, EMPTY,  EMPTY, EMPTY, EMPTY, BOX,   DEST,  WALL,  //
    WALL, EMPTY, EMPTY, EMPTY,  EMPTY, EMPTY, EMPTY, BOX,   DEST,  WALL,  //
    WALL, WALL,  WALL,  WALL,   WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  //
};

const int STAGE2_WIDTH = 8;
const int STAGE2_HEIGHT = 9;
const int STAGE2_MOVES = 50;
const MapField STAGE2[] = {
    EMPTY, EMPTY, WALL,   WALL,     WALL,  WALL,  WALL,  EMPTY,  //
    WALL,  WALL,  WALL,   EMPTY,    EMPTY, EMPTY, WALL,  EMPTY,  //
    WALL,  DEST,  PLAYER, BOX,      EMPTY, EMPTY, WALL,  EMPTY,  //
    WALL,  WALL,  WALL,   EMPTY,    BOX,   DEST,  WALL,  EMPTY,  //
    WALL,  DEST,  WALL,   WALL,     BOX,   EMPTY, WALL,  EMPTY,  //
    WALL,  EMPTY, WALL,   EMPTY,    DEST,  EMPTY, WALL,  WALL,   //
    WALL,  BOX,   EMPTY,  DEST_BOX, BOX,   BOX,   DEST,  WALL,   //
    WALL,  EMPTY, EMPTY,  EMPTY,    DEST,  EMPTY, EMPTY, WALL,   //
    WALL,  WALL,  WALL,   WALL,     WALL,  WALL,  WALL,  WALL,   //
};

const int STAGE3_WIDTH = 11;
const int STAGE3_HEIGHT = 9;
const int STAGE3_MOVES = 50;
const MapField STAGE3[] = {
    EMPTY, EMPTY,  EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, EMPTY, EMPTY,  //
    WALL,  WALL,   WALL,  WALL,  EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY,  //
    WALL,  EMPTY,  EMPTY, WALL,  BOX,   EMPTY, EMPTY, WALL,  WALL,  WALL,  WALL,  //
    WALL,  EMPTY,  BOX,   BOX,   EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  //
    WALL,  PLAYER, EMPTY, EMPTY, WALL,  BOX,   EMPTY, BOX,   WALL,  EMPTY, WALL,  //
    WALL,  WALL,   WALL,  EMPTY, WALL,  EMPTY, EMPTY, EMPTY, WALL,  EMPTY, WALL,  //
    WALL,  WALL,   EMPTY, EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, WALL,  //
    WALL,  WALL,   EMPTY, EMPTY, DEST,  DEST,  DEST,  DEST,  DEST,  EMPTY, WALL,  //
    WALL,  WALL,   WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  //
};

#endif